### ISSUE TITLE
Update to the TU patch

### ISSUE THREAD

**Issue by Mecripp** [linuxgurugamer/RecycledParts#1]
https://www.dropbox.com/s/ve6f07sapdcofw7/TexturesUnlimited_SpaceTuxIndustries_A2.zip?dl=0

This patch fixes some errors I made in the first one but it does have a TU textureswitch  that targets all parts that missing it if you know of away to write a MM to target just this mod that would be great it looks like @PART[*]:HAS[!MODULE[KSPTextureSwitch]]   and what I use on other mods is                                        @PART[*]:HAS[#manufacturer[NSS]]

**Comment by linuxgurugamer** [comment]
oh yuck I just saw this.
Is it still valid?
