### ISSUE TITLE
Installing Atomic Age addes a second air intake to each and every intake part

### ISSUE THREAD

**Issue by morphelianus** [linuxgurugamer/RecycledParts#10]
Well the short description explains pretty much already. Whenever I install Recycled Parts Atomic Age a second air intace is added to any intake part. Let's take the MK1 Divertless Supersonic Intake or Engine Nacelle. It doesen't matter if I install it with the Recycled Part bundle or as stand-alone mod without any other mods installed beside it. I tried this mod and encountered the issue since Kerbal 1.12.3 as I haven't used this mod earlier. You can find two screenshots of the same part attached pointing out the mentioned behaviour. Both screenshots are in german und unfortunatelly the second one could be a little bit better but it should clarfify the mentioned issue.
![Without Atomic Age](https://user-images.githubusercontent.com/2077318/213129563-099d9c4a-2d5c-4db6-9948-3bb4d4554fa3.png)
![With Atomic Age](https://user-images.githubusercontent.com/2077318/213131280-633b2eec-e15a-431b-a7ea-47e639a8674d.png)

**Comment by linuxgurugamer** [comment]
I found the problem, thanks for letting me know.
Watch for an update

**Comment by linuxgurugamer** [comment]
Actually, it's not a bug, just looks like it.

What's happening is that  the normal intake is dealing with IntakeAir, which is used for  air-breathing (and burning) engines.

This is need to create a new module to get a resource called IntakeAtm, which is used by the nuclear Jet Engine.

If you aren't using that, then you can just remove the file:  RecycledParts/AtomicAge/IntakeAtm.cfg
