### ISSUE TITLE
Upgrade parts to use part upgrade modules, and rebalance accordingly.

### ISSUE THREAD

**Issue by Ruedii** [linuxgurugamer/RecycledParts#3]
It would be incredibly useful to upgrade these parts to use part upgrade modules in the appropriate tree:

For Rocket engines this means:
Efficiency and power upgrades, better (or actual) alternators, less excess heat generation, more heat tolerance.

For air-breathing engines this means:
Efficiency, power, speed curve, and altitude curve upgrades, more heat tolerance, reduced excess heat production.

For air intakes this means:
Effective intake area, Effective intake volume, Speed curves, drag profile and heat tolerance.

For nuclear rockets this means:
Improvements to efficiency, power, heat tolerance and heat behavior.

For radiators this means
Improvements to efficiency, capabilities (e.g. how much of the ship it cools, and active radiator function), more heat tolerance and radiator power.

For command pods this means: 
Built in SAS functions, built in drone cores, stronger and more efficient reaction wheels, higher electrical capacity, better built in antenna.  (Still crap antenna.)  Adding a second (even crappier) antenna capable of short range science transmission.  (Likely requires a relay even from low kerbin orbit.) More temperature tolerance, more impact tolerance.

For crew cabins: More temperature tolerance

For drone core, same upgrades as command pods.

For antennas: Range upgrade, power efficiency upgrade.

For structural parts; More temperature tolerance, more heat tolerance, add fuel crossfeed, toggle fuel crossfeed option.

For solar panels, more output more impact tolerance, more heat tolerance. 

I think I have everything covered, but if not you get the idea.  Basically upgrades for everything.

Like all my blueprints I encourage anyone to work on them, obviously including myself.  Lets get these upgrades done one part at a time until they are all done.

**Comment by linuxgurugamer** [comment]
Of course it would be.

PRs are always welcome.

But, keep in mind that the upgrade functionality hasn't really been embraced by most people yet.  Also, upgrades should have some sort of graphical upgrade as well.
