### ISSUE TITLE
Too many .version files

### ISSUE THREAD

**Issue by HebaruSan** [linuxgurugamer/RecycledParts#5]
These are now all erroring out in the netkan bot:

- Too many .version files located: GameData/SpaceTuxIndustries/RecycledParts/RecycledParts.version, GameData/SpaceTuxIndustries/RecycledParts.version

http://status.ksp-ckan.org/

**Comment by linuxgurugamer** [comment]
Oh, yuck.
I'll get it fixed

**Comment by linuxgurugamer** [comment]
Fixed, lets see if that fixes CKAN (I was wondering why it was missing )

**Comment by HebaruSan** [comment]
Confirmed the new release is working.
