### ISSUE TITLE
Mod Request: Bahamutos Adjustable landing gear 

### ISSUE THREAD

**Issue by hooptiej** [linuxgurugamer/RecycledParts#8]
Mod Request: Bahamutos Adjustable landing gear

**Comment by hooptiej** [comment]
https://forum.kerbalspaceprogram.com/index.php?/topic/89874-105-adjustable-landing-gear-v120-masscost-scaling-tech-nodes-drag-may-30/

**Comment by linuxgurugamer** [comment]
This was folded into Kerbal Foundries a while ago
